Traceback (most recent call last):
  File "/home/runner/micromamba-root/envs/esm/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/micromamba-root/envs/esm/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/micromamba-root/envs/esm/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/micromamba-root/envs/esm/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/runner/micromamba-root/envs/esm/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/runner/micromamba-root/envs/esm/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba-root/envs/esm/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba-root/envs/esm/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = plt.figure(figsize=(7,7))

ax = plt.axes(projection=ccrs.epsg(3035))

nuts1.plot(
    ax=ax,
    edgecolor='black',
    facecolor='lightgrey'
)

gdf.to_crs(3035).plot(
    ax=ax,
    column='Fueltype',
    markersize=gdf.Capacity/20,
    legend=True
)

ax.set_extent([5, 19, 47, 55])
------------------

Traceback [0;36m(most recent call last)[0m:

[0m  File [1;32m~/micromamba-root/envs/esm/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3433[0m in [1;35mrun_code[0m
    exec(code_obj, self.user_global_ns, self.user_ns)[0m

[0m  Cell [1;32mIn [35], line 3[0m
    ax = plt.axes(projection=ccrs.epsg(3035))[0m

[0m  File [1;32m~/micromamba-root/envs/esm/lib/python3.9/site-packages/cartopy/crs.py:2540[0m in [1;35mepsg[0m
    return cartopy._epsg._EPSGProjection(code)[0m

[0m  File [1;32m~/micromamba-root/envs/esm/lib/python3.9/site-packages/cartopy/_epsg.py:30[0m in [1;35m__init__[0m
    projection = pyepsg.get(code)[0m

[0m  File [1;32m~/micromamba-root/envs/esm/lib/python3.9/site-packages/pyepsg.py:288[0m in [1;35mget[0m
    root = ET.fromstring(xml)[0m

[0;36m  File [0;32m~/micromamba-root/envs/esm/lib/python3.9/xml/etree/ElementTree.py:1347[0;36m in [0;35mXML[0;36m
[0;31m    parser.feed(text)[0;36m

[0;36m  File [0;32m<string>[0;36m[0m
[0;31mParseError[0m[0;31m:[0m not well-formed (invalid token): line 1, column 0

ParseError: not well-formed (invalid token): line 1, column 0 (<string>)

